In [1]:
import numpy as np

In [2]:
a = np.array([[10,20],
             [30,40],
             [50,60]])
b = np.array([1,2])

In [5]:
print a
print a.shape

[[10 20]
 [30 40]
 [50 60]]
(3, 2)


In [6]:
print b
print b.shape

[1 2]
(2,)


In [7]:
print a**2

[[ 100  400]
 [ 900 1600]
 [2500 3600]]


In [8]:
print np.mean(a)

35.0


In [13]:
print np.mean(a[:,0])
print np.mean(a[:,1])

30.0
40.0


In [15]:
print np.mean(a[0,:])
print np.mean(a[1,:])
print np.mean(a[2,:])

15.0
35.0
55.0


In [16]:
print np.sum(a)

210


In [19]:
print np.sum(a,axis=0)
print np.sum(a,axis=1)

[ 90 120]
[ 30  70 110]


In [20]:
print(a+b)

[[11 22]
 [31 42]
 [51 62]]


In [21]:
print(b-a)

[[ -9 -18]
 [-29 -38]
 [-49 -58]]


In [22]:
print np.absolute(b-a)

[[ 9 18]
 [29 38]
 [49 58]]


In [25]:
print np.sqrt(a)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]
 [7.07106781 7.74596669]]
